#!/usr/bin/bash
# Author: zenobit
# Description: Uses gum to provide a simple TUI
# License MIT

header() {
    gum style --padding '0 1' \
    --align center \
    --border rounded \
    --border-foreground "#295340" \
"Gum Make Executable
$(gum style --bold --foreground "#295340" 'chmod a+x') or
not $(gum style --bold --foreground "#295340" 'chmod a-x')"
}
header
if [ -n "${1}" ]; then
    file=${1}
else
    file=$(gum file \
    --cursor.foreground="#0BC51A" \
    --permissions.foreground="3" \
    --directory.foreground="#307edd" \
    --symlink.foreground="36" \
    --selected.foreground="#295340" \
    --file-size.foreground="8")
fi

if [ -x ${file} ]; then
    executable="exec"
else
    executable="not"
fi

if [ $executable == exec ]; then
    chmod a-x ${file}
elif [ $executable == not ]; then
    chmod a+x ${file}
fi
